name: Log Workflow Source

on:
  workflow_dispatch:

jobs:
  log-workflow-source:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log workflow source
        run: |
          echo "Workflow is running from: ${{ github.ref }}"
          
          # Extract the tag or branch name from github.ref
          if [[ ${{ github.ref }} == refs/tags/* ]]; then
            SOURCE="${{ github.ref#refs/tags/ }}"
            echo "Workflow is running from tag: $SOURCE"
          elif [[ ${{ github.ref }} == refs/heads/* ]]; then
            SOURCE="${{ github.ref#refs/heads/ }}"
            echo "Workflow is running from branch: $SOURCE"
          else
            SOURCE="${{ github.ref }}"
            echo "Workflow is running from: $SOURCE"
          fi

          echo "version file is $(cat version)"
          
          # You can use the SOURCE variable for further processing
          # For example:
          # - Run specific tests based on the tag/branch
          # - Deploy to different environments based on the tag/branch
          # - Generate reports or artifacts specific to the tag/branch