name: Deploy to UAT

on:
  workflow_dispatch:

jobs:
  log-workflow-source:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log workflow source
        run: |
          echo "Workflow is running from: ${{ github.ref }}"

          echo "version file is $(cat version)"
          echo "app file is $(cat app.txt)"
          echo "deploying to UAT"