name: Update Version and Tag Commit

on:
  push:
    branches:
      - main  # or any branch you want to trigger this action

permissions:
  contents: write  # This gives the GITHUB_TOKEN permission to modify repository contents

jobs:
  update-version-and-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all tags and branches

      - name: Read and update version
        id: version
        run: |
          # Read current version
          current_version=$(cat version)
          echo "Current version: $current_version"
          
          # Split version into major, minor, patch
          IFS='.' read -r major minor patch <<< "$current_version"
          
          # Increment minor version
          new_minor=$((minor + 1))
          new_version="$major.$new_minor.0"
          echo "New version: $new_version"
          
          # Update version file
          echo "$new_version" > version
          
          # Set output for later steps
          echo "new_version=$new_version" >> $GITHUB_OUTPUT

      - name: Commit updated version file
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add version
          git commit -m "Bump version to ${{ steps.version.outputs.new_version }}"
          git push

      - name: Create and push tag
        run: |
          git tag -a v${{ steps.version.outputs.new_version }} -m "Release version ${{ steps.version.outputs.new_version }}"
          git push origin v${{ steps.version.outputs.new_version }}